### PR TITLE
ImageProvider WebImage and WebApi

### PR DESCRIPTION
**Pull request by Tondorian**
This pull request add two new Image sources.
Since WebApi uses the MenuComands some heavy refactoring was required

### CODE REVIEW

**Comment by buchizo** [comment]
@Tondorian 
Thank you for your PR! I checked this PR, and I want to some updates.

- The image does not change to new image url  after change url in SingleWeb mode of option dialog.
- I guess `WebApi` mode is slideshow of web url. If possible, could you provide option's description or how-to-use?  What is mean about `JSON-Key` property?
- If possible, coud you provide full description for new properties. This extension support some langueges. (I translate it using AI :-)
- I like other porperty or enum name. for example `SlideshowWithWebApi`,  because it easy to understand how it works.

**Comment by Tondorian** [comment]
- The JSON-Key is used to point to the right part of the API-Response. For example https://developers.thecatapi.com/view-account/ylX4blBYT9FaoVd6OhvR?report=bOoHBz-8t The api response with multiple information and you have to "filter" the right prop for the url. So I added a prop to be able to support other apis,too. Maybe they store the URL in src or something else

**Comment by buchizo** [comment]
@Tondorian Thank you so much!

**Comment by Tondorian** [comment]
I think, I break the config.txt

**Comment by buchizo** [comment]
yes, I'll update few files.

**Pull request merged**
